// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Title?: string;
    Content?: any;
    Subtitle?: string;
    Description?: any;
    PublicationDate?: Date;
    slug: string;
    Cover?: { data: Media };
    Video?: { data: Media };
    Gallery?: { data: Media[] };
    Audios?: { data: Media[] };
    locale: string;
    localizations?: { data: Article[] };
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Content?: any;
  Subtitle?: string;
  Description?: any;
  PublicationDate?: Date;
  slug: string;
  Cover?: Media_Plain;
  Video?: Media_Plain;
  Gallery?: Media_Plain[];
  Audios?: Media_Plain[];
  locale: string;
  localizations?: Article_Plain[];
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Content?: any;
  Subtitle?: string;
  Description?: any;
  PublicationDate?: Date;
  slug: string;
  Cover?: number;
  Video?: number;
  Gallery?: number[];
  Audios?: number[];
  locale: string;
  localizations?: Article[];
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Content?: any;
  Subtitle?: string;
  Description?: any;
  PublicationDate?: Date;
  slug: string;
  Cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  Video?: AdminPanelRelationPropertyModification<Media_Plain>;
  Gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  Audios?: AdminPanelRelationPropertyModification<Media_Plain>[];
  locale: string;
  localizations?: Article[];
}
