// Interface automatically generated by schemas-to-ts

import { Citation } from './citation';
import { Citation_Plain } from './citation';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Author {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    FullName?: string;
    Firstname?: string;
    Lastname?: string;
    Title?: string;
    citations: { data: Citation[] };
    locale: string;
    localizations?: { data: Author[] };
  };
}
export interface Author_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  FullName?: string;
  Firstname?: string;
  Lastname?: string;
  Title?: string;
  citations: Citation_Plain[];
  locale: string;
  localizations?: Author_Plain[];
}

export interface Author_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  FullName?: string;
  Firstname?: string;
  Lastname?: string;
  Title?: string;
  citations: number[];
  locale: string;
  localizations?: Author[];
}

export interface Author_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  FullName?: string;
  Firstname?: string;
  Lastname?: string;
  Title?: string;
  citations: AdminPanelRelationPropertyModification<Citation_Plain>;
  locale: string;
  localizations?: Author[];
}
