// Interface automatically generated by schemas-to-ts

import { Author } from './author';
import { Author_Plain } from './author';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Citation {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Content: string;
    Source?: string;
    author?: { data: Author };
    locale: string;
    localizations?: { data: Citation[] };
  };
}
export interface Citation_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Content: string;
  Source?: string;
  author?: Author_Plain;
  locale: string;
  localizations?: Citation_Plain[];
}

export interface Citation_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Content: string;
  Source?: string;
  author?: number;
  locale: string;
  localizations?: Citation[];
}

export interface Citation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Content: string;
  Source?: string;
  author?: AdminPanelRelationPropertyModification<Author_Plain>;
  locale: string;
  localizations?: Citation[];
}
