// Interface automatically generated by schemas-to-ts

export interface Idea {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Subject: string;
    Description?: any;
    From?: string;
    Color?: any;
  };
}
export interface Idea_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Subject: string;
  Description?: any;
  From?: string;
  Color?: any;
}

export interface Idea_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Subject: string;
  Description?: any;
  From?: string;
  Color?: any;
}

export interface Idea_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Subject: string;
  Description?: any;
  From?: string;
  Color?: any;
}
