// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    title: string;
    richTextBlocks?: any;
    richTextMarkdown?: string;
    publicationDateTime?: Date;
    color?: any;
    slug: string;
    Cover?: { data: Media };
    TextsAsideImages?: any;
    locale: string;
    localizations?: { data: Page[] };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  richTextBlocks?: any;
  richTextMarkdown?: string;
  publicationDateTime?: Date;
  color?: any;
  slug: string;
  Cover?: Media_Plain;
  TextsAsideImages?: any;
  locale: string;
  localizations?: Page_Plain[];
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  richTextBlocks?: any;
  richTextMarkdown?: string;
  publicationDateTime?: Date;
  color?: any;
  slug: string;
  Cover?: number;
  TextsAsideImages?: any;
  locale: string;
  localizations?: Page[];
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title: string;
  richTextBlocks?: any;
  richTextMarkdown?: string;
  publicationDateTime?: Date;
  color?: any;
  slug: string;
  Cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  TextsAsideImages?: any;
  locale: string;
  localizations?: Page[];
}
