// Interface automatically generated by schemas-to-ts

import { TagsComponent } from '../components/shared/TagsComponent';
import { TagsComponent_Plain } from '../components/shared/TagsComponent';
import { TagsComponent_NoRelations } from '../components/shared/TagsComponent';

export interface Prayer {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    title?: string;
    content_plain?: string;
    subtitle?: string;
    name?: string;
    latin_reference?: string;
    uniqueFilename: string;
    authorName?: string;
    source?: string;
    indulgence?: string;
    tags: TagsComponent[];
    content?: string;
    information?: string;
    locale: string;
    localizations?: { data: Prayer[] };
  };
}
export interface Prayer_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  slug?: string;
  content_plain?: string;
  subtitle?: string;
  name?: string;
  latin_reference?: string;
  uniqueFilename: string;
  author_name?: string;
  source?: string;
  indulgence?: string;
  tags: TagsComponent_Plain[];
  content?: string;
  contentHtml?: string;
  contentInline?: string;
  shortInline?: string;
  information?: string;
  locale: string;
  localizations?: Prayer_Plain[];
}

export interface Prayer_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  content_plain?: string;
  subtitle?: string;
  name?: string;
  latin_reference?: string;
  uniqueFilename: string;
  authorName?: string;
  source?: string;
  indulgence?: string;
  tags: TagsComponent_NoRelations[];
  content?: string;
  information?: string;
  locale: string;
  localizations?: Prayer[];
}

export interface Prayer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  title?: string;
  content_plain?: string;
  subtitle?: string;
  name?: string;
  latin_reference?: string;
  uniqueFilename: string;
  authorName?: string;
  source?: string;
  indulgence?: string;
  tags: TagsComponent_Plain[];
  content?: string;
  information?: string;
  locale: string;
  localizations?: Prayer[];
}
