// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    description?: string;
    logo?: { data: Media };
    Cover?: { data: Media };
    Images?: { data: Media[] };
    locale: string;
    localizations?: { data: Project[] };
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  description?: string;
  logo?: Media_Plain;
  Cover?: Media_Plain;
  Images?: Media_Plain[];
  locale: string;
  localizations?: Project_Plain[];
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  description?: string;
  logo?: number;
  Cover?: number;
  Images?: number[];
  locale: string;
  localizations?: Project[];
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  description?: string;
  logo?: AdminPanelRelationPropertyModification<Media_Plain>;
  Cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  Images?: AdminPanelRelationPropertyModification<Media_Plain>[];
  locale: string;
  localizations?: Project[];
}
