// Interface automatically generated by schemas-to-ts

import { FetesComponent } from '../components/shared/FetesComponent';
import { TagsComponent } from '../components/shared/TagsComponent';
import { FetesComponent_Plain } from '../components/shared/FetesComponent';
import { TagsComponent_Plain } from '../components/shared/TagsComponent';
import { FetesComponent_NoRelations } from '../components/shared/FetesComponent';
import { TagsComponent_NoRelations } from '../components/shared/TagsComponent';

export interface Saint {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    name: string;
    dates: FetesComponent[];
    title?: string;
    calendar?: string;
    uniqueFilename: string;
    names: TagsComponent[];
    tags: TagsComponent[];
    information?: string;
    locale: string;
    localizations?: { data: Saint[] };
  };
}
export interface Saint_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  dates: FetesComponent_Plain[];
  title?: string;
  calendar?: string;
  uniqueFilename: string;
  names: TagsComponent_Plain[];
  tags: TagsComponent_Plain[];
  information?: string;
  locale: string;
  localizations?: Saint_Plain[];
}

export interface Saint_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  dates: FetesComponent_NoRelations[];
  title?: string;
  calendar?: string;
  uniqueFilename: string;
  names: TagsComponent_NoRelations[];
  tags: TagsComponent_NoRelations[];
  information?: string;
  locale: string;
  localizations?: Saint[];
}

export interface Saint_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  name: string;
  dates: FetesComponent_Plain[];
  title?: string;
  calendar?: string;
  uniqueFilename: string;
  names: TagsComponent_Plain[];
  tags: TagsComponent_Plain[];
  information?: string;
  locale: string;
  localizations?: Saint[];
}
