name = "www-gilles-dev"
compatibility_date = "2022-07-12"

workers_dev = true
preview_urls = false

routes = [
    { pattern = "gilles.dev", custom_domain = true }
]

[assets]
directory = "dist/app/browser"
not_found_handling = "single-page-application"

[build]
command = "sh script/cibuild.sh"
cwd = "./"
watch_dir = "./src/*"

