// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface ImageAsideTextComponent {
  text?: string;
  images?: { data: Media[] };
  imageLeft: boolean;
}
export interface ImageAsideTextComponent_Plain {
  text?: string;
  images?: Media_Plain[];
  imageLeft: boolean;
}

export interface ImageAsideTextComponent_NoRelations {
  text?: string;
  images?: number[];
  imageLeft: boolean;
}
