// Interface automatically generated by schemas-to-ts

export enum CategoryEnum {
  Blog = 'blog',
  Now = 'now',
  About = 'about',
  Idea = 'idea',
  Portfolio = 'portfolio',
}

export interface ClassificationComponent {
  Category?: CategoryEnum;
}
export interface ClassificationComponent_Plain {
  Category?: CategoryEnum;
}

export interface ClassificationComponent_NoRelations {
  Category?: CategoryEnum;
}
