// Interface automatically generated by schemas-to-ts

export interface EmailLabelComponent {
  email: string;
  label?: string;
}
export interface EmailLabelComponent_Plain {
  email: string;
  label?: string;
}

export interface EmailLabelComponent_NoRelations {
  email: string;
  label?: string;
}
