// Interface automatically generated by schemas-to-ts

export interface FetesComponent {
  date: Date;
  label?: string;
}
export interface FetesComponent_Plain {
  date: Date;
  label?: string;
}

export interface FetesComponent_NoRelations {
  date: Date;
  label?: string;
}
