// Interface automatically generated by schemas-to-ts

export enum NameEnum {
  Wrkng = 'wrkng',
  Gilles = 'gilles',
  Etorate = 'etorate',
  Mdiv = 'mdiv',
  Vitrine = 'vitrine',
}

export interface ProjectComponent {
  name?: NameEnum;
}
export interface ProjectComponent_Plain {
  name?: NameEnum;
}

export interface ProjectComponent_NoRelations {
  name?: NameEnum;
}
