// Interface automatically generated by schemas-to-ts

export interface TagsComponent {
  value?: string;
}
export interface TagsComponent_Plain {
  value?: string;
}

export interface TagsComponent_NoRelations {
  value?: string;
}
