// Interface automatically generated by schemas-to-ts

export interface UrlLabelComponent {
  url: string;
  label?: string;
}
export interface UrlLabelComponent_Plain {
  url: string;
  label?: string;
}

export interface UrlLabelComponent_NoRelations {
  url: string;
  label?: string;
}
