#! /bin/bash
#MISE description="Launch the server on prod"
#MISE alias="dcd"

check_docker() {
  if ! docker info > /dev/null 2>&1; then
    echo "⚠️ Error: Docker Engine is not running!"
    echo "👉 Tip: Start Docker Desktop or run 'sudo systemctl start docker'"
    exit 1
  fi
}

# Call before executing docker compose commands
check_docker

docker compose down

