name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with Corepack
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # Step 3: Enable Corepack and install dependencies
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: yarn install

      # Step 4: Build the Angular app using your prod script
      - name: Build
        run: yarn prod

      # Step 5: Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/gilles.dev/browser
          branch: gh-pages
